name: fair-checker-env
channels:
  - conda-forge
  - defaults
dependencies:
  - gunicorn==20.1.0
  - eventlet==0.30.2
  - Flask==2.0.2
  - Flask-Cors==3.0.10
  - Flask-SocketIO==5.1.1
  - Flask-Caching==1.10.1
  - rdflib==6.1.1
  - rich==10.12.0
  - pyshacl==0.17.3
  - selenium==3.141.0
  - sparqlwrapper==1.8.5
  - validators==0.18.2
  - python-dotenv==0.19.1
  - pymongo==3.11.0
  - termcolor==1.1.0
  - tqdm==4.62.3
  - webdriver-manager==3.5.0
  - flake8==3.7.9
  - pytest==6.2.5
  - coverage==6.2
  - pandas
  - gitpython
  - pip
  - pip:
      - extruct==0.13.0
